version: '3.8'

services:
  sender:
    build: ./sender
    depends_on:
      - server
    restart: always
    volumes:
      - ./data:/app/data

  server:
    build: ./server
    ports:
      - "5555:5555"
    # environment:
    #   - FLASK_APP=app.py
    #   - FLASK_ENV=production
    volumes:
      - ./server:/app
    restart: always